export const enlaces = [
  {
    id: 1,
    name: "Inicio",
    name2: "Home",
    enlace: "/",
  },
  {
    id: 2,
    name: "Proyectos",
    name2: "Projects",
    enlace: "/projects",
  },
  {
    id: 3,
    name: "Catálogo",
    name2: "Stones",
    enlace: "/stones",
  },
  {
    id: 4,
    name: "Nosotros",
    name2: "About",
    enlace: "/about",
  },
  {
    id: 5,
    name: "Simulador",
    name2: "Simulator",
    enlace: "/simulator",
  },
  {
    id: 6,
    name: "Contacto",
    name2: "Contact",
    enlace: "/contact",
  },
];

export const imagesParallax = [
  {
    id: 1,
    imagen: "/home/1.jpeg",
    alt: "primera",
  },
  {
    id: 2,
    imagen: "/home/1.jpeg",
    alt: "segunda",
  },
];

export const imagesParallax2 = [
  {
    id: 1,
    imagen: "/social/03.jpg",
    alt: "primera2",
  },
  {
    id: 2,
    imagen: "/social/03.jpg",
    alt: "segunda2",
  },
];

export const imagesParallax3 = [
  {
    id: 1,
    imagen: "/home/importaciones.jpeg",
    alt: "primera2",
  },
  {
    id: 2,
    imagen: "/home/importaciones.jpeg",
    alt: "segunda2",
  },
];

export const imagesInfiniteScroll = [
  {
    id: 1,
    imagen: "/social/01.jpg",
    alt: "albercas",
    title: "Anatole France 310",

    enlace: "https://www.instagram.com/p/C3yOavKMMAx/",
  },
  {
    id: 2,
    imagen: "/social/02.jpg",
    alt: "alberca-grande",
    title: "Plaza del Valle",

    enlace: "https://www.instagram.com/p/C4gk-GPtm8q/",
  },

  {
    id: 3,
    imagen: "/social/03.jpg",
    alt: "casa",
    title: "Millet",

    enlace: "https://www.instagram.com/p/C48r9SJLugK/",
  },

  {
    id: 4,
    imagen: "/social/04.jpg",
    alt: "edificio",
    title: "Corporativo Enlace",

    enlace: "https://www.instagram.com/p/C5WpmgFNZOo/",
  },
  {
    id: 5,
    imagen: "/social/05.jpg",
    alt: "departamentos",
    title: "Chicago 60",

    enlace: "https://www.instagram.com/p/C6W6n5wtOz9/",
  },
  {
    id: 6,
    imagen: "/social/06.jpg",
    alt: "departamentos",
    title: "Chicago 60",

    enlace: "https://www.instagram.com/p/CukPxYdvESi/",
  },
];

export const clientes = [
  {
    id: 1,
    imagen: "/proyectos/10.jpg",
    alt: "albercas",
    title: "Anatole France 310",
    description: "Col. San José Vista Hermosa CDMX",
  },
  {
    id: 2,
    imagen: "/proyectos/07.jpg",
    alt: "alberca-grande",
    title: "Plaza del Valle",
    description: "Tulum Quintana Roo",
  },

  {
    id: 3,
    imagen: "/proyectos/08.jpg",
    alt: "casa",
    title: "Millet",
    description: "Col. Bosques de las lomas CDMX",
  },

  {
    id: 4,
    imagen: "/proyectos/05.jpg",
    alt: "edificio",
    title: "Corporativo Enlace",
    description: "Col. Polanco CDMX",
  },
  {
    id: 5,
    imagen: "/proyectos/06.jpg",
    alt: "departamentos",
    title: "Chicago 60",
    description: "Miami Florida",
  },
];

export const GalleryImages = [
  {
    id: 11,
    imagen: "/proyectos/11.jpg",
    alt: "uno",
    title: "Hotel Naala",
    description: "Tulum, Quintana Roo",
    categoria: "cdmx",
  },

  {
    id: 10,
    imagen: "/proyectos/10.jpg",
    alt: "uno",
    title: "Anatole France 310",
    description: "Col. Polanco CDMX",
    categoria: "cdmx",
  },

  {
    id: 9,
    imagen: "/proyectos/09.jpg",
    alt: "uno",
    title: "Casa Bosques",
    description: "Col. Bosque de las Lomas CDMX",
    categoria: "cdmx",
  },

  {
    id: 26,
    imagen: "/proyectos/26.webp",
    alt: "uno",
    title: "Shark Tower",
    description: "Cancún",
    categoria: "nacional",
  },
  {
    id: 27,
    imagen: "/proyectos/27.jpg",
    alt: "uno",
    title: "Altezza Bosques",
    description: "México",
    categoria: "nacional",
  },
  {
    id: 28,
    imagen: "/proyectos/28.jpg",
    alt: "uno",
    title: "Remodelación Hotel Marquis Reforma",
    description: "Ciudad de México",
    categoria: "cdmx",
  },

  {
    id: 8,
    imagen: "/proyectos/08.jpg",
    alt: "uno",
    title: "Millet",
    description: "Col. Extremadura Insurgentes CDMX",
    categoria: "cdmx",
  },

  {
    id: 12,
    imagen: "/proyectos/12.jpg",
    alt: "uno",
    title: "Departamento Miami",
    description: "Miami Florida",
    categoria: "internacional",
  },
  {
    id: 13,
    imagen: "/proyectos/13.jpg",
    alt: "uno",
    title: "Departamento Acapulco Diamante",
    description: "Acapulco Diamante",
    categoria: "nacional",
  },
  {
    id: 14,
    imagen: "/proyectos/14.jpg",
    alt: "uno",
    title: "Residencial Tamaulipas",
    description: "Col. Condesa CDMX",
    categoria: "cdmx",
  },
  {
    id: 15,
    imagen: "/proyectos/15.jpg",
    alt: "uno",
    title: "Club House Bosques",
    description: "Col. Bosques de las Lomas CDMX",
    categoria: "cdmx",
  },
  {
    id: 16,
    imagen: "/proyectos/16.jpg",
    alt: "uno",
    title: "Residencial Oasis",
    description: "Col. San José Vista Hermosa CDMX",
    categoria: "cdmx",
  },
  {
    id: 17,
    imagen: "/proyectos/17.jpg",
    alt: "uno",
    title: "Hard Rock",
    description: "Punta Cana República Dominicana",
    descrip2: "Punta Cana, Dominican Republic",
    categoria: "internacional",
  },
  {
    id: 18,
    imagen: "/proyectos/18.jpg",
    alt: "uno",
    title: "Royalton Chic Uvero Alto",
    description: "Punta Cana República Dominicana",
    descrip2: "Punta Cana, Dominican Republic",
    categoria: "internacional",
  },
  {
    id: 19,
    imagen: "/proyectos/19.jpg",
    alt: "uno",
    title: "Royalton Chic Antigua y Barbuda",
    description: "",
    categoria: "internacional",
  },
  {
    id: 20,
    imagen: "/proyectos/20.jpg",
    alt: "uno",
    title: "Royalton Bavaro",
    description: "",
    categoria: "internacional",
  },
  {
    id: 21,
    imagen: "/proyectos/21.jpg",
    alt: "uno",
    title: "Dreams Macao Beach",
    description: "Punta Cana República Dominicana",
    descrip2: "Punta Cana, Dominican Republic",
    categoria: "internacional",
  },
  {
    id: 22,
    imagen: "/proyectos/22.jpg",
    alt: "dos",
    title: "Banyan Tree Valle de Guadalupe",
    description: "Baja California México",
    categoria: "nacional",
  },
  {
    id: 23,
    imagen: "/proyectos/23.jpg",
    alt: "tres",
    title: "Remodelación Camino Real Aeropuerto",
    description: "México",
    categoria: "nacional",
  },
  {
    id: 24,
    imagen: "/proyectos/24.jpg",
    alt: "cuatro",
    title: "Villas Campo de Golf",
    description: "Mérida Yucatán",
    categoria: "nacional",
  },
  {
    id: 25,
    imagen: "/proyectos/25.jpg",
    alt: "uno",
    title: "Beautiful Tulum",
    description: "Mar Caribe",
    categoria: "internacional",
  },

  {
    id: 1,
    imagen: "/proyectos/01.jpg",
    alt: "uno",
    title: "Torre Cervantes 251",
    description: "Col. Polanco CDMX",
    categoria: "cdmx",
  },
  {
    id: 2,
    imagen: "/proyectos/02.jpg",
    alt: "dos",
    title: "Tecoyotitla 301",
    description: "Col. Florida CDMX",
    categoria: "cdmx",
  },
  {
    id: 3,
    imagen: "/proyectos/03.jpg",
    alt: "tres",
    title: "Residencial Dmas",
    description: "Col. San José Insurgentes CDMX",
    categoria: "cdmx",
  },
  {
    id: 4,
    imagen: "/proyectos/04.jpg",
    alt: "cuatro",
    title: "Espacio Escandón",
    description: "Col. Escandón CDMX",
    categoria: "cdmx",
  },
  {
    id: 5,
    imagen: "/proyectos/05.jpg",
    alt: "uno",
    title: "Corporativo Enlace",
    description: "Col. Del Valle Sur CDMX",
    categoria: "cdmx",
  },
  {
    id: 6,
    imagen: "/proyectos/06.jpg",
    alt: "uno",
    title: "Chicago 60",
    description: "Col. Nápoles CDMX",
    categoria: "cdmx",
  },
  {
    id: 7,
    imagen: "/proyectos/07.jpg",
    alt: "uno",
    title: "Plaza del Valle",
    description: "Col. del Valle CDMX",
    categoria: "cdmx",
  },
];

export const filterProjects = [
  {
    id: 1,
    categoria: "todos",
    title: "Todos",
    title2: "All",
  },
  {
    id: 2,
    categoria: "cdmx",
    title: "Ciudad de México",
    title2: "Mexico City",
  },
  {
    id: 3,
    categoria: "internacional",
    title: "Internacionales",
    title2: "International",
  },
];

export const categorias = [
  {
    id: 1,
    categoria: "todas",
    title: "Todas",
    title2: "All",
  },
  {
    id: 2,
    categoria: "marmoles",
    title: "Mármoles",
    title2: "Marbles",
  },
  {
    id: 3,

    categoria: "granitos",
    title: "Granitos",
    title2: "Granites",
  },
  {
    id: 4,
    categoria: "cuarcitas",
    title: "Cuarcitas",
    title2: "Quartzites",
  },
  {
    id: 4,
    categoria: "calizas",
    title: "Calizas",
    title2: "Limestone",
  },
  {
    id: 5,
    categoria: "travertinos",
    title: "Travertinos",
    title2: "Travertine",
  },
];

export const catalogo = [
  {
    id: 1,
    title: "Mármol Amber Brown",
    categoria: "marmoles",
    imagen: "/marmol/01.webp",
    alt: "",
  },
  {
    id: 2,
    title: "Mármol Aqua Black",
    categoria: "marmoles",
    imagen: "/marmol/02.webp",
    alt: "",
  },
  {
    id: 3,
    title: "Mármol Arabescato Corchia",
    categoria: "/",
    imagen: "/marmol/03.webp",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Oro",
    categoria: "marmoles",
    imagen: "/marmol/04.webp",
    alt: "",
  },
  {
    id: 5,
    title: "Mármol Arabescato Vagli",
    categoria: "marmoles",
    imagen: "/marmol/05.webp",
    alt: "",
  },
  {
    id: 6,
    title: "Mármol Athens Wood",
    categoria: "marmoles",
    imagen: "/marmol/06.webp",
    alt: "",
  },
  {
    id: 7,
    title: "Mármol Bardiglio Capella",
    categoria: "marmoles",
    imagen: "/marmol/07.webp",
    alt: "",
  },
  {
    id: 8,
    title: "Mármol Bardiglio Imperial",
    categoria: "marmoles",
    imagen: "/marmol/08.webp",
    alt: "",
  },
  {
    id: 9,
    title: "Mármol Bianco Carrara",
    categoria: "marmoles",
    imagen: "/marmol/09.webp",
    alt: "",
  },
  {
    id: 10,
    title: "Mármol Bianco Perlino",
    categoria: "marmoles",
    imagen: "/marmol/10.webp",
    alt: "",
  },
  {
    id: 11,
    title: "Mármol Bianco Statuario Venat",
    categoria: "marmoles",
    imagen: "/marmol/11.webp",
    alt: "",
  },
  {
    id: 12,
    title: "Mármol Bianco Statuario Venat",
    categoria: "marmoles",
    imagen: "/marmol/12.webp",
    alt: "",
  },
  {
    id: 13,
    title: "Mármol Black Wood",
    categoria: "marmoles",
    imagen: "/marmol/13.webp",
    alt: "",
  },
  {
    id: 14,
    title: "Mármol Botticino Royal",
    categoria: "marmoles",
    imagen: "/marmol/14.webp",
    alt: "",
  },
  {
    id: 15,
    title: "Mármol Calacatta Clasico",
    categoria: "marmoles",
    imagen: "/marmol/15.webp",
    alt: "",
  },
  {
    id: 16,
    title: "Mármol Crema Marfil",
    categoria: "marmoles",
    imagen: "/marmol/16.webp",
    alt: "",
  },
  {
    id: 17,
    title: "Mármol Dorado Tepexi",
    categoria: "marmoles",
    imagen: "/marmol/17.webp",
    alt: "",
  },
  {
    id: 18,
    title: "Mármol Equator",
    categoria: "marmoles",
    imagen: "/marmol/18.webp",
    alt: "",
  },
  {
    id: 19,
    title: "Mármol Eramosa",
    categoria: "marmoles",
    imagen: "/marmol/19.webp",
    alt: "",
  },
  {
    id: 20,
    title: "Mármol Galala",
    categoria: "marmoles",
    imagen: "/marmol/20.webp",
    alt: "",
  },
  {
    id: 21,
    title: "Mármol Grey Damasco",
    categoria: "marmoles",
    imagen: "/marmol/21.webp",
    alt: "",
  },
  {
    id: 22,
    title: "Mármol Grey Wood",
    categoria: "marmoles",
    imagen: "/marmol/22.webp",
    alt: "",
  },
  {
    id: 23,
    title: "Mármol Grigio Modena",
    categoria: "marmoles",
    imagen: "/marmol/23.webp",
    alt: "",
  },
  {
    id: 24,
    title: "Mármol Marron Emperador Light",
    categoria: "marmoles",
    imagen: "/marmol/24.webp",
    alt: "",
  },
  {
    id: 25,
    title: "Mármol Marron Emperador",
    categoria: "marmoles",
    imagen: "/marmol/25.webp",
    alt: "",
  },
  {
    id: 26,
    title: "Mármol Nero Marquinha",
    categoria: "marmoles",
    imagen: "/marmol/26.webp",
    alt: "",
  },
  {
    id: 27,
    title: "Mármol Nestos Beige",
    categoria: "marmoles",
    imagen: "/marmol/27.webp",
    alt: "",
  },
  {
    id: 28,
    title: "Mármol Perlino Cross",
    categoria: "marmoles",
    imagen: "/marmol/28.webp",
    alt: "",
  },
  {
    id: 29,
    title: "Mármol Pietra Grey",
    categoria: "marmoles",
    imagen: "/marmol/29.webp",
    alt: "",
  },
  {
    id: 30,
    title: "Mármol Polaris",
    categoria: "marmoles",
    imagen: "/marmol/30.webp",
    alt: "",
  },
  {
    id: 31,
    title: "Mármol Portoro Extra Vena Fina",
    categoria: "marmoles",
    imagen: "/marmol/31.webp",
    alt: "",
  },
  {
    id: 32,
    title: "Rain Forest Green",
    categoria: "marmoles",
    imagen: "/marmol/32.webp",
    alt: "",
  },
  {
    id: 33,
    title: "Mármol Raymond White",
    categoria: "marmoles",
    imagen: "/marmol/33.webp",
    alt: "",
  },
  {
    id: 34,
    title: "Mármol Sunny",
    categoria: "marmoles",
    imagen: "/marmol/34.webp",
    alt: "",
  },
  {
    id: 35,
    title: "Mármol Rojo Alicante",
    categoria: "marmoles",
    imagen: "/marmol/35.webp",
    alt: "",
  },
  {
    id: 36,
    title: "Mármol Volga Grey",
    categoria: "marmoles",
    imagen: "/marmol/36.webp",
    alt: "",
  },
  {
    id: 37,
    title: "Mármol Sahara Noir",
    categoria: "marmoles",
    imagen: "/marmol/37.webp",
    alt: "",
  },
  {
    id: 38,
    title: "Mármol Santo Tomas",
    categoria: "marmoles",
    imagen: "/marmol/38.webp",
    alt: "",
  },
  {
    id: 39,
    title: "Mármol Silk Georgette",
    categoria: "marmoles",
    imagen: "/marmol/39.webp",
    alt: "",
  },
  {
    id: 40,
    title: "Mármol Silvia",
    categoria: "marmoles",
    imagen: "/marmol/40.webp",
    alt: "",
  },
  {
    id: 41,
    title: "Mármol Sivec",
    categoria: "marmoles",
    imagen: "/marmol/41.webp",
    alt: "",
  },
  {
    id: 42,
    title: "Mármol Thunder Black",
    categoria: "marmoles",
    imagen: "/marmol/42.webp",
    alt: "",
  },
  {
    id: 43,
    title: "Mármol Statuarietto",
    categoria: "marmoles",
    imagen: "/marmol/43.webp",
    alt: "",
  },
  {
    id: 44,
    title: "Mármol Nero Dorato",
    categoria: "marmoles",
    imagen: "/marmol/44.webp",
    alt: "",
  },
  {
    id: 45,
    title: "Mármol Bardilgio New York",
    categoria: "marmoles",
    imagen: "/marmol/45.webp",
    alt: "",
  },
  {
    id: 46,
    title: "Mármol Lilac",
    categoria: "marmoles",
    imagen: "/marmol/46.webp",
    alt: "",
  },
  {
    id: 47,
    title: "Mármol Grigio Carnico",
    categoria: "marmoles",
    imagen: "/marmol/47.webp",
    alt: "",
  },
  {
    id: 48,
    title: "Mármol Portoro Silver",
    categoria: "marmoles",
    imagen: "/marmol/48.webp",
    alt: "",
  },
  {
    id: 49,
    title: "Mármol Vermont Beige",
    categoria: "marmoles",
    imagen: "/marmol/49.webp",
    alt: "",
  },
  {
    id: 50,
    title: "Mármol Pierre Bleu",
    categoria: "marmoles",
    imagen: "/marmol/50.webp",
    alt: "",
  },
  {
    id: 51,
    title: "Mármol Gris Rochelle",
    categoria: "marmoles",
    imagen: "/marmol/51.webp",
    alt: "",
  },
  {
    id: 52,
    title: "Mármol Cappuccino",
    categoria: "marmoles",
    imagen: "/marmol/52.webp",
    alt: "",
  },
  {
    id: 53,
    title: "Mármol Arabescato Grigio",
    categoria: "marmoles",
    imagen: "/marmol/53.webp",
    alt: "",
  },
  {
    id: 54,
    title: "Mármol Amber Brown",
    categoria: "marmoles",
    imagen: "/marmol/54.webp",
    alt: "",
  },
  {
    id: 55,
    title: "Mármol Tundra Grey",
    categoria: "marmoles",
    imagen: "/marmol/55.webp",
    alt: "",
  },
  {
    id: 56,
    title: "Mármol Venato",
    categoria: "marmoles",
    imagen: "/marmol/56.webp",
    alt: "",
  },
  {
    id: 57,
    title: "Mármol Zebrino",
    categoria: "marmoles",
    imagen: "/marmol/57.webp",
    alt: "",
  },
  {
    id: 58,
    title: "Mármol Scorpio",
    categoria: "marmoles",
    imagen: "/marmol/58.webp",
    alt: "",
  },
  {
    id: 59,
    title: "Mármol Gris Rochelle",
    categoria: "marmoles",
    imagen: "/marmol/59.webp",
    alt: "",
  },
  {
    id: 60,
    title: "Mármol Amani Bronze",
    categoria: "marmoles",
    imagen: "/marmol/60.webp",
    alt: "",
  },
  {
    id: 62,
    title: "Mármol Rain Forest Green",
    categoria: "marmoles",
    imagen: "/marmol/62.webp",
    alt: "",
  },
  {
    id: 64,
    title: "Mármol Soap Stone",
    categoria: "marmoles",
    imagen: "/marmol/64.webp",
    alt: "",
  },
  {
    id: 66,
    title: "Mármol Blanco Carrara",
    categoria: "marmoles",
    imagen: "/marmol/66.webp",
    alt: "",
  },
  {
    id: 69,
    title: "Mármol Verias Green",
    categoria: "marmoles",
    imagen: "/marmol/69.webp",
    alt: "",
  },
  {
    id: 70,
    title: "Mármol Calacatta Verde",
    categoria: "marmoles",
    imagen: "/marmol/70.webp",
    alt: "",
  },
  {
    id: 71,
    title: "Mármol Cipollino Black",
    categoria: "marmoles",
    imagen: "/marmol/71.webp",
    alt: "",
  },
  {
    id: 72,
    title: "Mármol Cote D'azur Galaxy",
    categoria: "marmoles",
    imagen: "/marmol/72.webp",
    alt: "",
  },
  {
    id: 73,
    title: "Mármol Cote D'azur",
    categoria: "marmoles",
    imagen: "/marmol/73.webp",
    alt: "",
  },
  {
    id: 74,
    title: "Mármol Noir Blanc",
    categoria: "marmoles",
    imagen: "/marmol/74.webp",
    alt: "",
  },

  // Granitos
  {
    id: 75,
    title: "Granito Virginia Mist",
    categoria: "granitos",
    imagen: "/granito/01.webp",
    alt: "",
  },
  {
    id: 76,
    title: "Granito Ala de Mosca",
    categoria: "granitos",
    imagen: "/granito/02.webp",
    alt: "",
  },
  {
    id: 77,
    title: "Granito Black Galaxy",
    categoria: "granitos",
    imagen: "/granito/03.webp",
    alt: "",
  },
  {
    id: 78,
    title: "Granito Blanco Dallas",
    categoria: "granitos",
    imagen: "/granito/04.webp",
    alt: "",
  },
  {
    id: 79,
    title: "Granito Sea Wave White",
    categoria: "granitos",
    imagen: "/granito/05.webp",
    alt: "",
  },
  {
    id: 80,
    title: "Verde Ubatuba",
    categoria: "granitos",
    imagen: "/granito/06.webp",
    alt: "",
  },
  {
    id: 81,
    title: "Granito Santa Cecilia",
    categoria: "granitos",
    imagen: "/granito/07.webp",
    alt: "",
  },
  {
    id: 82,
    title: "Granito Ebony",
    categoria: "granitos",
    imagen: "/granito/08.webp",
    alt: "",
  },
  {
    id: 83,
    title: "Granito Ebony Cristal",
    categoria: "granitos",
    imagen: "/granito/09.webp",
    alt: "",
  },
  {
    id: 84,
    title: "Granito Gris Oxford",
    categoria: "granitos",
    imagen: "/granito/10.webp",
    alt: "",
  },
  {
    id: 85,
    title: "Granito Negro Absoluto",
    categoria: "granitos",
    imagen: "/granito/11.webp",
    alt: "",
  },
  {
    id: 86,
    title: "Granito Black Vermont",
    categoria: "granitos",
    imagen: "/granito/12.webp",
    alt: "",
  },
  {
    id: 87,
    title: "Granito Verde Bamboo",
    categoria: "granitos",
    imagen: "/granito/13.webp",
    alt: "",
  },
  {
    id: 88,
    title: "Granito Metalicus",
    categoria: "granitos",
    imagen: "/granito/14.webp",
    alt: "",
  },
  {
    id: 89,
    title: "Granito Oscuro Mist",
    categoria: "granitos",
    imagen: "/granito/15.webp",
    alt: "",
  },
  {
    id: 90,
    title: "Granito Zimbabwe Lino",
    categoria: "granitos",
    imagen: "/granito/16.webp",
    alt: "",
  },
  {
    id: 91,
    title: "Granito Titanium",
    categoria: "granitos",
    imagen: "/granito/17.webp",
    alt: "",
  },
  {
    id: 92,
    title: "Granito Ice Blue",
    categoria: "granitos",
    imagen: "/granito/18.webp",
    alt: "",
  },
  {
    id: 93,
    title: "Granito Via Láctea",
    categoria: "granitos",
    imagen: "/granito/19.webp",
    alt: "",
  },
  {
    id: 94,
    title: "Granito Lava Vecchia",
    categoria: "granitos",
    imagen: "/granito/20.webp",
    alt: "",
  },
  {
    id: 95,
    title: "Granito Negro Zimbabwe Linear",
    categoria: "granitos",
    imagen: "/granito/21.webp",
    alt: "",
  },
  {
    id: 96,
    title: "Granito Lucerna",
    categoria: "granitos",
    imagen: "/granito/22.webp",
    alt: "",
  },
  {
    id: 97,
    title: "Granito Magma Gold",
    categoria: "granitos",
    imagen: "/granito/23.webp",
    alt: "",
  },

  {
    id: 100,
    title: "Granito Virginia Mist",
    categoria: "granitos",
    imagen: "/granito/26.webp",
    alt: "",
  },
  {
    id: 102,
    title: "Granito Lucerna",
    categoria: "granitos",
    imagen: "/granito/28.webp",
    alt: "",
  },
  {
    id: 103,
    title: "Granito Black Vermont",
    categoria: "granitos",
    imagen: "/granito/29.webp",
    alt: "",
  },
  {
    id: 104,
    title: "Granito Negro Zimbawe",
    categoria: "granitos",
    imagen: "/granito/30.webp",
    alt: "",
  },

  // Cuarcitas
  {
    id: 113,
    title: "Alexandrita",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/01.jpg",
    alt: "",
  },
  {
    id: 115,
    title: "Andes",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/02.jpg",
    alt: "",
  },
  {
    id: 116,
    title: "Aquarela",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/03.webp",
    alt: "",
  },
  {
    id: 117,
    title: "Armani",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/04.jpg",
    alt: "",
  },
  {
    id: 118,
    title: "Azurra Bay",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/05.webp",
    alt: "",
  },
  {
    id: 119,
    title: "Bianco Superiore",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/06.webp",
    alt: "",
  },
  {
    id: 120,
    title: "Blue Crystal",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/07.webp",
    alt: "",
  },
  {
    id: 121,
    title: "Blue Deep",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/08.jpg",
    alt: "",
  },
  {
    id: 122,
    title: "Blue Macaubas",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/09.webp",
    alt: "",
  },
  {
    id: 123,
    title: "Blue Maldives",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/10.jpg",
    alt: "",
  },
  {
    id: 124,
    title: "Blue Roma",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/11.webp",
    alt: "",
  },
  {
    id: 125,
    title: "Brilliant Grey",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/12.jpg",
    alt: "",
  },
  {
    id: 126,
    title: "Calacatta Lux",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/13.jpg",
    alt: "",
  },
  {
    id: 127,
    title: "Casablanca",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/14.webp",
    alt: "",
  },
  {
    id: 128,
    title: "Chantilly",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/15.webp",
    alt: "",
  },
  {
    id: 129,
    title: "Colonato",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/16.webp",
    alt: "",
  },
  {
    id: 130,
    title: "Cosmopolitan",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/17.webp",
    alt: "",
  },
  {
    id: 131,
    title: "Crystal Milk",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/18.webp",
    alt: "",
  },
  {
    id: 132,
    title: "Crystal Supreme",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/19.webp",
    alt: "",
  },
  {
    id: 133,
    title: "Da Vinci",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/20.webp",
    alt: "",
  },
  {
    id: 134,
    title: "Denali",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/21.jpg",
    alt: "",
  },
  {
    id: 135,
    title: "Diamond Black",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/22.webp",
    alt: "",
  },
  {
    id: 136,
    title: "Eiger Alps",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/23.webp",
    alt: "",
  },
  {
    id: 137,
    title: "Explosion Blue",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/24.webp",
    alt: "",
  },
  {
    id: 138,
    title: "Fantasy Lux",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/25.jpg",
    alt: "",
  },
  {
    id: 139,
    title: "Fusion Crystal",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/26.webp",
    alt: "",
  },
  {
    id: 140,
    title: "Fusion Dark",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/27.webp",
    alt: "",
  },
  {
    id: 141,
    title: "Fusion Light",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/28.jpg",
    alt: "",
  },
  {
    id: 142,
    title: "Ijen Blue",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/29.jpg",
    alt: "",
  },
  {
    id: 143,
    title: "Infinity Grey",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/30.jpg",
    alt: "",
  },
  {
    id: 144,
    title: "J’Adore",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/31.jpg",
    alt: "",
  },
  {
    id: 145,
    title: "Juliet",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/32.webp",
    alt: "",
  },
  {
    id: 146,
    title: "Mont Blanc",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/33.webp",
    alt: "",
  },
  {
    id: 147,
    title: "Morium Crystal",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/34.webp",
    alt: "",
  },
  {
    id: 148,
    title: "Naica",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/35.webp",
    alt: "",
  },
  {
    id: 149,
    title: "Naica Blue",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/36.webp",
    alt: "",
  },
  {
    id: 150,
    title: "Persa Green",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/37.jpg",
    alt: "",
  },
  {
    id: 151,
    title: "Raggio D’Luna",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/38.jpg",
    alt: "",
  },
  {
    id: 152,
    title: "Roma Imperiale",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/39.webp",
    alt: "",
  },
  {
    id: 153,
    title: "Splendido",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/40.jpg",
    alt: "",
  },
  {
    id: 154,
    title: "Sunshine",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/41.webp",
    alt: "",
  },
  {
    id: 155,
    title: "Taj Mahal",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/42.jpg",
    alt: "",
  },
  {
    id: 156,
    title: "Vitra",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/43.jpg",
    alt: "",
  },
  {
    id: 157,
    title: "Volupia Maestro",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/44.webp",
    alt: "",
  },
  {
    id: 158,
    title: "White Lux",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/45.jpg",
    alt: "",
  },
  {
    id: 159,
    title: "Yosemite",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/46.jpg",
    alt: "",
  },

  // Calizas

  {
    id: 160,
    title: "Arenisca Arcoíris",
    title2: "Rainbow Sandstone",
    categoria: "calizas",
    imagen: "/calizas/01.jpg",
    alt: "",
  },
  {
    id: 161,
    title: "Piedra Amarilla de Vicenza",
    title2: "Pietra Gialla di Vicenza",
    categoria: "calizas",
    imagen: "/calizas/02.jpg",
    alt: "",
  },
  {
    id: 162,
    title: "Masai",
    title2: "Masai",
    categoria: "calizas",
    imagen: "/calizas/03.jpg",
    alt: "",
  },
  {
    id: 163,
    title: "",
    categoria: "calizas",
    imagen: "/calizas/04.jpg",
    alt: "",
  },
  {
    id: 164,
    title: "Crema Moka",
    title2: "Moka Cream",
    categoria: "calizas",
    imagen: "/calizas/05.jpg",
    alt: "",
  },
  {
    id: 165,
    title: "Tala Beige",
    title2: "Tala Beige",
    categoria: "calizas",
    imagen: "/calizas/01.jpg",
    alt: "",
  },

  // Travertinos

  {
    id: 166,
    title: "Travertino Panteón",
    title2: "Travertino Pantheon",
    categoria: "travertinos",
    imagen: "/travertinos/01.jpg",
    alt: "",
  },
  {
    id: 167,
    title: "Travertino Blanco",
    title2: "Travertino Bianco",
    categoria: "travertinos",
    imagen: "/travertinos/02.jpeg",
    alt: "",
  },
  {
    id: 168,
    title: "Travertino Plata",
    title2: "Travertino Silver",
    categoria: "travertinos",
    imagen: "/travertinos/03.jpeg",
    alt: "",
  },
  {
    id: 169,
    title: "Travertino Plata Oceánico",
    title2: "Ocean Silver Travertine",
    categoria: "travertinos",
    imagen: "/travertinos/04.jpeg",
    alt: "",
  },
  {
    id: 170,
    title: "Travertino Rojo",
    title2: "Travertino Rosso",
    categoria: "travertinos",
    imagen: "/travertinos/05.jpg",
    alt: "",
  },
  {
    id: 171,
    title: "Travertino Navona",
    title2: "Travertino Navona",
    categoria: "travertinos",
    imagen: "/travertinos/06.jpg",
    alt: "",
  },
  {
    id: 172,
    title: "Travertino Estriado",
    title2: "Travertino Striato",
    categoria: "travertinos",
    imagen: "/travertinos/07.jpeg",
    alt: "",
  },
  {
    id: 173,
    title: "Travertino Romano Clásico",
    title2: "Travertino Romano Classico",
    categoria: "travertinos",
    imagen: "/travertinos/08.jpg",
    alt: "",
  },
  {
    id: 174,
    title: "Travertino Alabastrino",
    title2: "Travertino Alabastrino",
    categoria: "travertinos",
    imagen: "/travertinos/09.jpeg",
    alt: "",
  },
  {
    id: 175,
    title: "Travertino Giallo",
    title2: "Travertino Giallo",
    categoria: "travertinos",
    imagen: "/travertinos/10.jpg",
    alt: "",
  },
  {
    id: 176,
    title: "Travertino Noce",
    title2: "Travertino Noce",
    categoria: "travertinos",
    imagen: "/travertinos/11.jpg",
    alt: "",
  },
  {
    id: 177,
    title: "Travertino Paglierino",
    title2: "Travertino Paglierino",
    categoria: "travertinos",
    imagen: "/travertinos/12.jpeg",
    alt: "",
  },
];

export const simulador = [
  {
    id: 1,
    title: "Crystal Milk",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/18.webp",
    alt: "",
  },
  {
    id: 2,
    title: "Sunshine",
    categoria: "cuarcitas",
    imagen: "/cuarcitas/41.webp",
    alt: "",
  },
  {
    id: 3,
    title: "Mármol Venato",
    categoria: "marmoles",
    imagen: "/marmol/56.webp",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Orobico",
    categoria: "marmoles",
    imagen: "/marmol/Arabescato_Orobico.webp",
    alt: "",
  },
];

export const sala_uno = [
  {
    id: 1,
    title: "Crystal Milk",
    categoria: "sala-grande",
    imagen: "/simulador/modelos/sala1_02.jpg",
    alt: "",
  },

  {
    id: 2,
    title: "Sunshine",
    categoria: "sala-grande",
    imagen: "/simulador/modelos/sala1_03.jpg",
    alt: "",
  },

  {
    id: 3,
    title: "Mármol Venato",
    categoria: "sala-grande",
    imagen: "/simulador/modelos/sala1_01.jpg",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Orobico",
    categoria: "sala-grande",
    imagen: "/simulador/modelos/sala1_04.jpg",
    alt: "",
  },
];

export const sala_dos = [
  {
    id: 1,
    title: "Crystal Milk",
    categoria: "sala-chica",
    imagen: "/simulador/modelos/sala2_02.jpg",
    alt: "",
  },

  {
    id: 2,
    title: "Sunshine",
    categoria: "sala-chica",
    imagen: "/simulador/modelos/sala2_03.jpg",
    alt: "",
  },

  {
    id: 3,
    title: "Mármol Venato",
    categoria: "sala-chica",
    imagen: "/simulador/modelos/sala2_01.jpg",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Orobico",
    categoria: "sala-chica",
    imagen: "/simulador/modelos/sala2_04.jpg",
    alt: "",
  },
  
];

export const sanitario_uno = [
  {
    id: 1,
    title: "Crystal Milk",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario1_02.jpg",
    alt: "",
  },

  {
    id: 2,
    title: "Sunshine",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario1_03.jpg",
    alt: "",
  },

  {
    id: 3,
    title: "Mármol Venato",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario1_01.jpg",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Orobico",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario1_04.jpg",
    alt: "",
  },
  
]

export const sanitario_dos = [
  {
    id: 1,
    title: "Crystal Milk",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario2_02.jpg",
    alt: "",
  },

  {
    id: 2,
    title: "Sunshine",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario2_03.jpg",
    alt: "",
  },

  {
    id: 3,
    title: "Mármol Venato",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario2_01.jpg",
    alt: "",
  },
  {
    id: 4,
    title: "Mármol Arabescato Orobico",
    categoria: "sanitario",
    imagen: "/simulador/modelos/sanitario2_04.jpg",
    alt: "",
  },
  
]